---
- name: Install the required packages
  apt: pkg=haproxy state=installed

- name: Enable HAProxy
  template: src=haproxy_enable.j2 dest=/etc/default/haproxy
  notify: Restart haproxy

- name: Write config file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: Reload haproxy

- name: Make sure haproxy is started and enabled
  service: name=haproxy state=started enabled=yes
