---
- hosts: mesos-slaves
  gather_facts: false
  sudo: yes

  roles:
    - common
    - { role: mesosphere, tags: [ 'mesos' ] }
    - { role: marathon, tags: [ 'marathon'], marathon_run_mode: bridge }
